export const strings = {
  app: {
    name: "Bawa Apa?",
    taglineSerious: "Smart packing checklist for wherever you're going.",
    taglineFun: "Biar yang ketinggalan cuma mantan.",
  },
  home: {
    inputPlaceholder: "Mau pergi ke mana atau melakukan apa?",
    createChecklist: "Buat Checklist",
    quickMode: "Quick Mode",
    detailMode: "Detail Mode",
    presets: "Preset aktivitas",
    recent: "Checklist terakhir",
    emptyRecent: "Belum ada checklist. Mulai dengan menulis aktivitasmu.",
    thinking: "Menyiapkan checklist…",
    inputHint: "Contoh: “Besok ke kampus buat presentasi, naik motor, dari pagi sampai sore.”",
  },
  checklist: {
    required: "Wajib",
    recommended: "Disarankan",
    optional: "Opsional",
    addItem: "Tambah barang",
    addItemPlaceholder: "Nama barang…",
    whatsMissing: "Apa ada yang kurang?",
    saveAsTemplate: "Simpan sebagai template",
    imLeaving: "Saya Mau Berangkat",
    reason: "Alasan",
    aiBadge: "AI",
    checkingAi: "Saya cek lagi barang bawaanmu…",
    aiOffline: "AI tidak tersedia sekarang. Checklist lokal tetap jalan.",
    reviewNoFindings: "Sepertinya sudah lengkap. Siap berangkat!",
    reviewTitle: "Beberapa hal untuk dicek",
    templateSaved: "Tersimpan sebagai template.",
    emptyItems: "Belum ada barang. Tambahkan secara manual di bawah.",
    notFound: "Checklist tidak ditemukan.",
  },
  progress: {
    ready: (done: number, total: number) => `${done} / ${total} barang siap`,
    percent: (p: number) => `Packing readiness: ${p}%`,
    notReady: "Belum siap",
    almostReady: "Hampir siap",
    readyToGo: "Siap berangkat",
    allDone: "Semua siap. Tinggal berangkat. 🎒",
    someLeft: (n: number) => `Sedikit lagi. Masih ada ${n} barang yang belum masuk.`,
  },
  finalCheck: {
    title: (n: number) => `${n} barang penting belum siap:`,
    allReady: "Semua barang penting sudah siap. Berangkat! 🎒",
    back: "Kembali ke checklist",
  },
  history: {
    title: "Riwayat",
    search: "Cari checklist…",
    empty: "Belum ada riwayat checklist.",
    open: "Buka lagi",
    duplicate: "Duplikat",
    delete: "Hapus",
    items: (n: number) => `${n} barang`,
  },
  templates: {
    title: "Template",
    builtIn: "Template bawaan",
    yours: "Template kamu",
    use: "Pakai",
    edit: "Edit",
    duplicate: "Duplikat",
    delete: "Hapus",
    empty: "Belum ada template pribadi.",
  },
  settings: {
    title: "Pengaturan",
    theme: "Tema",
    language: "Bahasa",
    notifications: "Notifikasi",
    ai: "AI",
    weather: "Cuaca",
    privacy: "Privasi",
    clearData: "Hapus data lokal",
    clearDataConfirm: "Hapus semua data lokal? Tindakan ini tidak bisa dibatalkan.",
    aiHint: "AI hanya menambah saran. Checklist tetap dibuat lokal.",
    cleared: "Data lokal dihapus.",
  },
  nav: {
    home: "Home",
    history: "Riwayat",
    templates: "Template",
    settings: "Pengaturan",
  },
  common: {
    offline: "Kamu sedang offline. Checklist tetap bisa dipakai.",
    emptyState: "Mau pergi ke mana hari ini?",
    cancel: "Batal",
    save: "Simpan",
    add: "Tambah",
    accept: "Terima",
    dismiss: "Abaikan",
    back: "Kembali",
    on: "Aktif",
    off: "Nonaktif",
  },
} as const;
